### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by logidelic** [excamera/AWSLambdaFace#4]
This is very nice! I'm just starting out with both OpenFace and Lambda, but I do have a performance question. In my initial tests with AWSLambdaFace, calls to both recognize_face and train_face_recognizer take several seconds to return the result. Is this to be expected or is there something weird here?

**Comment by jremmons** [comment]
As is, the code is pretty slow (it takes several seconds for me too). This is not to say that it couldn't be made much faster though. Both the `recognize_face` and `train_face_recognizer` do lots of dumb things (the most expensive dumb thing being downloading a 200MB tarball from S3 on every invocation! This could be cached, but I didn't implement it yet).

**Comment by logidelic** [comment]
Thanks for the quick response! If I continue to go down this path, I may try to tackle it myself. Regardless, thanks for the nifty code!

**Comment by jremmons** [comment]
Let me know if you decide to hack on the code. I would be willing to help as much as I can!
