### ISSUE TITLE
Video input?

### ISSUE THREAD

**Issue by xdsv** [excamera/AWSLambdaFace#5]
Does it work for video input? Like the one in your blog?
In the README you only mention image examples.

**Comment by jremmons** [comment]
The code in this repo is setup to work with image data only. The demo I described in the blog post uses the same code though! The exact code I used for the demo is in the [NSDI17](https://github.com/excamera/AWSLambdaFace/tree/nsdi17) branch, but it would require quite a bit of massaging to get it working though...
